config/routes.rb
SearchRecipes::Application.routes.draw do

  devise_for :users
  root to: "recipes#index"
  post '/search' => 'recipes#search'
  get '/search' => 'recipes#search'
  get '/save_to_collection' => 'recipes#save_to_collection'
  get '/remove_recipe' => 'recipes#remove_recipe'
  get 'collection' => 'collections#index'

  resources :recipes

  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
	belongs_to :user
	has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :collection
	
	def self.search_for(query)
		where('ingredient Like :query', query: "%#{query}%")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :collection
  has_many :recipes, through: :collection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
	def index
		@collection = current_user.collection
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_filter :authenticate_user!

	def index
	end

	def search
		@recipe = params[:ingredient]
		base_endpoint_url = "http://api.yummly.com/v1/api/recipes?_app_id=#{ENV['APP_ID']}&_app_key=#{ENV['APP_KEY']}&maxResult=50&"
		#base_endpoint_url = "http://api.yummly.com/v1/api/recipes?_app_id=bc196f8d&_app_key=959d599a14211e9c9afd49bd0f43cdcf&maxResult=50&"     
	    
	    if @recipe.include? ","
	    	ingredients = @recipe.split(",").map {|ingredient| ingredient.strip }
	    else
	    	ingredients = @recipe.split
	    end

	    url_safe_ingredients = ingredients.inject(String.new) { |safe_url, ingredient| safe_url << "allowedIngredient[]=#{ingredient}&" }
		compiled_url = base_endpoint_url + url_safe_ingredients
		formatted_url = compiled_url.gsub(/&$/, '')
		response = RestClient.get(formatted_url)

		parsed_response = JSON.parse(response)
		@recipes = parsed_response["matches"].sort_by { |response| response["ingredients"].count }
		@recipe_image = ""
	end

	def save_to_collection
		current_user.build_collection if current_user.collection.nil?
		current_user.save
		current_user.collection.recipes.create(name: params["name"], image_url: params["image_url"], ingredient: params["ingredient"], instruction_url: params["instruction_url"])
		current_user.save
		redirect_to collection_path
	end

	def remove_recipe
		@recipe = current_user.collection.recipes.find(params[:id])
		@recipe.destroy

		redirect_to collection_path
	end

	private

	def safe_recipe_params
	    params.require('recipe').permit(:ingredient)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/collections/index.html.erb
<div class="row">
  
<div id="container" class="js-masonry"
  data-masonry-options='{"itemSelector": ".col-md-4" }'>

<% @collection.recipes.each do |recipe| %>		
	<div class="col-md-4">
			<div class="thumbnail">
				<% if recipe.name.nil? %>
				<%= image_tag "http://placehold.it/350x200" %>
				<% else %>
				<%= image_tag "#{recipe.image_url}" %>
				<% end %>
				<div class="caption">
				<h3><%= recipe.name %></h3>
				<h5>Ingredients: <%= recipe.ingredient %></h5>
				<a href="<%= recipe.instruction_url %>" class="btn btn-info" role="button">Get Recipe on Yummly!</a>
				<div class="addAndRemove"><%= link_to "", remove_recipe_path(id: recipe.id), :class => "glyphicon glyphicon-remove", :style=> "text-decoration: none; color: #FC4349;"  %></div>
				</div>
			</div>
		</div>
	<% end %>

   <a href="#top" id="top-link"><h2><span class="glyphicon glyphicon-arrow-up"></span></h2></a>

</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchRecipes</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    $( document ).ready(function() {
      var $container = $('.js-masonry');
      $container.imagesLoaded( function() {
        $container.masonry('layout');
      });
    });

  // scroll to top plugin
  jQuery.fn.topLink = function(settings) {
    settings = jQuery.extend({
      min: 1,
      fadeSpeed: 100
    }, settings);
    return this.each(function() {
      //listen for scroll
      var el = jQuery(this);
      el.hide(); //in case the user forgot
      jQuery(window).scroll(function() {
        if(jQuery(window).scrollTop() >= settings.min)
        {
          el.fadeIn(settings.fadeSpeed);
        }
        else
        {
          el.fadeOut(settings.fadeSpeed);
        }
      });
    });
  };

  //usage w/ smoothscroll
  jQuery(document).ready(function() {
    //set the link
    jQuery('#top-link').topLink({
      min: 500,
      fadeSpeed: 100
    });
    //smoothscroll
    jQuery('#top-link').click(function(r) {    
      jQuery("html, body").animate({ scrollTop: 0 }, 300);
    });
  });

  </script>
</head>
<body style="background: url('<%= asset_path('bg3.jpg' ) %>') no-repeat 25% 95% fixed;" >
<!-- Background photo by Zsuzsanna Kilian -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Recipes', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Search", root_path %></li>
            <li><%= link_to "My Collection", collection_path %></li>
          </ul>
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>

    <div class="container">
      <%= render 'layouts/messages' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_tag '/search', method: :post do %>
	<div class="input-group input-group-lg">
  <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
	<%= text_field_tag :ingredient, 'Search recipes', class: 'form-control recipes-form'  %>
<% end %>
</div>

app/views/recipes/collection.html.erb
<div class="row">
<div id="container" class="js-masonry"
  data-masonry-options='{"itemSelector": ".col-md-4" }'>
	<% @recipes.map do |recipe| %>
		<div class="col-md-4">
			<div class="thumbnail">
				<% if recipe.name.nil? %>
				<%= image_tag "http://placehold.it/350x200" %>
				<% else %>
				<%= image_tag "#{recipe.image_url}" %>
				<% end %>
				<div class="caption">
				<h3><%= recipe.name %></h3>
				<h5>Ingredients: <%= recipe.ingredient %></h5>
				<p><a href="#{recipe.instruction_url}" class="btn btn-info" role="button">Get Recipe on Yummly!</a></p>
				<%= link_to "/remove_recipe", yummly_id: recipe["id"] %>
				</div>
			</div>
		</div>
	<% end %>

   <a href="#top" id="top-link"><h2><span class="glyphicon glyphicon-arrow-up"></span></h2></a>

</div>
</div>

app/views/recipes/index.html.erb
<div class="row" >
  	<div class="col-md-6 col-md-offset-3">
		<div class="text-center"><h1>Dont' feel like going out to eat? Type what's in your fridge below. </h1></div>
		<br />
		<%= render 'form' %>
  	</div>
</div>

app/views/recipes/search.html.erb
<%= render 'form' %>
<br /><br />

<div class="row">
<div id="container" class="js-masonry"
  data-masonry-options='{"itemSelector": ".col-md-4" }'>

	<% @recipes.map do |recipe| %>
		<div class="col-md-4">
			<div class="thumbnail">
				<% if recipe['imageUrlsBySize'].nil? %>
					<%= image_tag "http://placehold.it/350x200" %>
					<% @recipe_image = "http://placehold.it/350x200" %>
				<% else %>
					<%= image_tag "#{recipe['imageUrlsBySize']['90'].gsub(/\=s90\-c$/, '')}" %>
					<% @recipe_image = "#{recipe['imageUrlsBySize']['90'].gsub(/\=s90\-c$/, '')}" %>
				<% end %>
				<div class="caption">
				<h3><%= recipe["recipeName"] %></h3>
				<h5>Rating: <span class="badge badge-warning"><%= recipe["rating"] %></span></h5>
				<h5>Ingredients: <%= recipe["ingredients"].join(", ") %></h5>
				<a href="http://www.yummly.com/recipe/<%= recipe["id"] %>" class="btn btn-info" role="button">Get Recipe on Yummly!</a>
				
				<div class="addAndRemove"><%= link_to "", save_to_collection_path(name: recipe["recipeName"], image_url: @recipe_image, ingredient: recipe["ingredients"].join(", "), instruction_url: "http://www.yummly.com/recipe/#{recipe["id"]}"), :class => "glyphicon glyphicon-plus", :style=> "text-decoration: none; color: #999;"  %></div>
				</div>
			</div>
		</div>
	<% end %>

   <a href="#top" id="top-link"><h2><span class="glyphicon glyphicon-arrow-up"></span></h2></a>

</div>
</div>